// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:1080059959906:web:25c0b398d0e99728810f3b',
    messagingSenderId: '1080059959906',
    projectId: 'profilescreensapp',
    authDomain: 'profilescreensapp.firebaseapp.com',
    storageBucket: 'profilescreensapp.firebasestorage.app',
    measurementId: 'G-QJ8E5E3W5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo4Sui_HTElvqlAOyGYQqDwxQmdysHDMI',
    appId: '1:1080059959906:android:ed50b3555759a6dc810f3b',
    messagingSenderId: '1080059959906',
    projectId: 'profilescreensapp',
    storageBucket: 'profilescreensapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5qs6ni6sBWtlhkJXdwhJ4dCct-J31E4',
    appId: '1:1080059959906:ios:13db4548735da16b810f3b',
    messagingSenderId: '1080059959906',
    projectId: 'profilescreensapp',
    storageBucket: 'profilescreensapp.firebasestorage.app',
    iosBundleId: 'com.example.profileScreens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5qs6ni6sBWtlhkJXdwhJ4dCct-J31E4',
    appId: '1:1080059959906:ios:13db4548735da16b810f3b',
    messagingSenderId: '1080059959906',
    projectId: 'profilescreensapp',
    storageBucket: 'profilescreensapp.firebasestorage.app',
    iosBundleId: 'com.example.profileScreens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnKF0lg0uF33ywtLt32lFMgcLs-329MyY',
    appId: '1:1080059959906:web:abe1bb13ec6c28a9810f3b',
    messagingSenderId: '1080059959906',
    projectId: 'profilescreensapp',
    authDomain: 'profilescreensapp.firebaseapp.com',
    storageBucket: 'profilescreensapp.firebasestorage.app',
    measurementId: 'G-3Q8PQGN5S3',
  );
}
